export const state = {
    FR_CCD_REFER_TO_JUDGE_STATE: 'referredToJudge',
    SSCS_CCD_APPEAL_CREATED: 'appealCreated',
    COH_STARTED_STATE: 'continuous_online_hearing_started',
    COH_DECISION_ISSUED_STATE: 'continuous_online_hearing_decision_issued',
    COH_RELISTED_STATE: 'continuous_online_hearing_relisted',
    COH_Q_QUESTION_DRAFTED_STATE: 'question_drafted',
    COH_Q_QUESTION_ISSUE_PENDING_STATE: 'question_issue_pending',
    COH_Q_QUESTION_ISSUED_STATE: 'question_issued',
    COH_Q_DEADLINE_ELAPSED_STATE: 'question_deadline_elapsed',
    COH_Q_DEADLINE_EXT_ELAPSED_STATE: 'question_deadline_extension_elapsed',
    COH_Q_QUESTION_DEADLINE_EXTENTION_GRANTED_STATE: 'question_deadline_extension_granted',
    COH_Q_QUESTION_DEADLINE_EXTENSION_DENIED_STATE: 'question_deadline_extension_denied',
    COH_A_QUESTION_ANSWERED_STATE: 'question_answered',
    SSCS: [
        'appealCreated',
        'continuous_online_hearing_started',
        'continuous_online_hearing_decision_issued',
        'question_drafted',
        'question_issued',
        'question_answered',
        'question_deadline_elapsed',
        'question_deadline_extension_elapsed',
        'question_deadline_extension_granted',
    ],
    FR: [
        'consentOrderMade',
        'awaitingPaymentResponse',
        'awaitingHWFDecision',
        'caseAdded',
        'consentOrderApproved',
        'referredToJudge',
        'applicationIssued',
    ],
    DIV: [
        'AwaitingPayment',
        'AosAwaiting',
        'AosStarted',
        'AosCompletedAwaitingAnswer',
        'AosCompleted',
        'AwaitingHWFDecision',
        'AwaitingDecreeNisi',
    ],
    PRO: ['BOExamining', 'PAAppCreated', 'CasePrinted', 'CaseCreated', 'CasePaymentFailed'],
    CMC: ['open'],
}
